### ISSUE TITLE
Missing GWPS metadata

### ISSUE THREAD

**Issue by andysw90** [recursionpharma/EFAAR_benchmarking#78]
Hi, thanks for the fantastic tool. 

`notebooks/map_evaluation_comparison.ipynb`, in the "Load stored map data" chunk, wants to load `data/GWPS_metadata.pkl`, but is missing from the repo. I can obviously regenerate from `map_building_benchmarking`, but it seems like it's supposed to be in `data` already so that I can run without rebuilding the maps?

Thanks a lot

**Comment by safiyecelik** [comment]
@andysw90 thanks for pointing this out! Just added the file to `notebooks/data/GWPS_metadata.pkl`. Note that it is tracked through `lfs` like the other large files.
